variables:
  ROOT: ${ROOT}
  CLUSTER_NAME: ${CLUSTER_NAME}
  REGION: ${REGION}
  PROJECT: ${PROJECT}
  NAMESPACE: ${NAMESPACE}
  # HELM_REPO_URL: ${HELM_REPO_URL}

stages:
  - deploy-dev
  - view
  - takedown

# Reusable job to deploy app to gke using helm
.deploy-to-gke:
  stage: deploy-dev
  image: google/cloud-sdk
  script:
    - echo "Deploying app..."
    # Install helm
    - curl https://baltocdn.com/helm/signing.asc | apt-key add -
    - apt-get install apt-transport-https --yes
    - echo "deb https://baltocdn.com/helm/stable/debian/ all main" | tee /etc/apt/sources.list.d/helm-stable-debian.list
    - apt-get update
    - apt-get install helm
    
    # Authenticate to GCP
    - gcloud auth activate-service-account --key-file ${ROOT}/serviceaccount.json
    - gcloud container clusters get-credentials ${CLUSTER_NAME} --region=${REGION} --project=${PROJECT}
    # Install helm release
    - helm install boutique-app1 boutique-chart/ --namespace ${NAMESPACE}
    # Check the installed releases
    - helm ls
  environment: development

# Reusable job to view deployed app
.verify-deployment:
  stage: view
  script:
    - gcloud auth activate-service-account --key-file ${ROOT}/serviceaccount.json
    - gcloud container clusters get-credentials ${CLUSTER_NAME} --region=${REGION} --project=${PROJECT}
    - kubectl get all

# Reusable job to remove deployed app
.remove-deployment:
  stage: takedown
  when: manual
  script:
    - echo "Taking down application"
    - gcloud auth activate-service-account --key-file ${ROOT}/serviceaccount.json
    - gcloud container clusters get-credentials ${CLUSTER_NAME} --region=${REGION} --project=${PROJECT}
    - kubectl get deployments -n ${NAMESPACE}
    - kubectl delete deployments --all -n ${NAMESPACE}

# Use reusable jobs in pipeline
deploy-dev:
  extends: .deploy-to-gke
  only:
    - main

view-app:
  extends: .verify-deployment
  dependencies:
    - deploy-dev
  only:
    - main

remove-app:
  extends: .remove-deployment
  dependencies:
    - deploy-dev
    - view-app
  only:
    - main
