variables:
  ROOT: ${ROOT}
  GCLOUD_SDK: ${GCLOUD_SDK}
  CLUSTER_NAME: ${CLUSTER_NAME}
  REGION: ${REGION}
  PROJECT: ${PROJECT}
  NAMESPACE: ${NAMESPACE}
  HELM_REPO_URL: ${HELM_REPO_URL}
  # MANIFEST: ${MANIFEST}

stages:
  - deploy-dev
  - view
  - takedown

# Reusable job to deploy app to gke using helm
.deploy-to-gke:
  stage: deploy-dev
  image: google/cloud-sdk
  script:
    - echo "Deploying app..."
    - ls -al
    - gcloud auth activate-service-account --key-file ${ROOT}/serviceaccount.json
    - gcloud container clusters get-credentials ${CLUSTER_NAME} --region=${REGION} --project=${PROJECT}
    - helm repo add boutique ${HELM_REPO_URL}
    # - helm repo update
    - helm install --namespace helm-boutique-app --repo https://storage.googleapis.com/helm-bucket-repo-test/boutique-chart boutique-chart boutique
    # - kubectl apply -f ${MANIFEST}
  environment: development

# Reusable job to view deployed app
.verify-deployment:
  stage: view
  script:
    - gcloud auth activate-service-account --key-file ${ROOT}/serviceaccount.json
    - gcloud container clusters get-credentials ${CLUSTER_NAME} --region=${REGION} --project=${PROJECT}
    - kubectl get all

# Reusable job to remove deployed app
.remove-deployment:
  stage: takedown
  when: manual
  script:
    - echo "Taking down application"
    - gcloud auth activate-service-account --key-file ${ROOT}/serviceaccount.json
    - gcloud container clusters get-credentials ${CLUSTER_NAME} --region=${REGION} --project=${PROJECT}
    - kubectl get deployments -n ${NAMESPACE}
    - kubectl delete deployments --all -n ${NAMESPACE}

# Use reusable jobs in pipeline
deploy-dev:
  extends: .deploy-to-gke
  only:
    - main

view-app:
  extends: .verify-deployment
  dependencies:
    - deploy-dev
  only:
    - main

remove-app:
  extends: .remove-deployment
  dependencies:
    - deploy-dev
    - view-app
  only:
    - main
